Bump black from 20.08b1 to 23.3.0 (PR #110)
The previous version was using typed-ast, which broke in Python 3.9.8:

```
poetry run black --check --quiet .
Traceback (most recent call last):
  File "/home/runner/work/cmdlib/cmdlib/.venv/bin/black", line 5, in <module>
    from black import patched_main
  File "/home/runner/work/cmdlib/cmdlib/.venv/lib/python3.9/site-packages/black/__init__.py", line 52, in <module>
    from typed_ast import ast3, ast27
  File "/home/runner/work/cmdlib/cmdlib/.venv/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
    from typed_ast import _ast3
ImportError: /home/runner/work/cmdlib/cmdlib/.venv/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape
make: *** [Makefile:35: check-fmt] Error 1
```

See: https://github.com/python/typed_ast/issues/169