Upgrade poetry to version 1.0.10
This is required to support Python 3.9, as poetry 1.0.5 fails with the
following error:

```
poetry install && touch .venv/updated
Traceback (most recent call last):
  File "/home/runner/.poetry/bin/poetry", line 9, in <module>
    from poetry.console import main
  File "/home/runner/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/runner/.poetry/lib/poetry/console/application.py", line 1, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
```

because `poetry/_vendor` does not have a `py3.9` directory (it was
added in 1.0.10).